project:
  type: website
  output-dir: docs

website:
  title: "Maggie Moss"
  favicon: favicon.png
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/maggiemoss96
      - icon: linkedin
        href: https://www.linkedin.com/in/maggiejmoss/
      - icon: envelope
        href: mailto:maggie.moss@colostate.edu

  page-footer:
    center: |
      © 2025 Maggie Moss • Built with Quarto  
      <a href="https://github.com/maggiemoss96/maggiemoss96.github.io">Site Source</a>

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
