project:
  type: website
  output-dir: docs

website:
  title: "Maggie Moss"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About Page.qmd
      - Research Website Page.qmd
      - Teaching Page.qmd
      - CV Page.qmd

page-footer:
    center: |
      © 2025 Maggie Moss • Built with Quarto  
      <a href="https://github.com/maggiemoss96/maggiemoss96.github.io">Site Source</a>      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

