project:
  type: website
  output-dir: docs

website:
  title: "maggiemoss96"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - About Page.qmd
      - Research Website Page.qmd
      - Teaching Page.qmd
      - CV Page.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

