---
title: "About"
---

Maggie Moss is a Geosciences PhD student at Colorado State University studying the geochemistry and petrology of the Yellowstone Plateau Volcanic Field's basaltic magma system. Moss holds a Master of Urban Planning degree from New York University, where she focused on natural hazards and city planning. Her background in petrography, field geology, and physical volcanology began as an undergraduate at George Washington University, where she received a Luther Rice Fellowship to study silicic volcanism associated with Yellowstone’s third caldera cycle.

Moss recently received the Jack Kleinman Memorial Foundation grant to support her fieldwork, as well as funding from the Colorado Scientific Society to launch an undergraduate mentorship program that has engaged six high-achieving students in summer fieldwork and four in ongoing laboratory research. She also leads an interdisciplinary team synthesizing geochemical and geophysical data to develop a conceptual model of the magmatic plumbing system at Akutan, one of the USGS’s very high-threat volcanoes.

In the first year of her Ph.D., Moss successfully planned and executed a month of fieldwork in Yellowstone National Park, mapping and sampling the Junction Butte basalt, Undine Falls basalt, and the basalt of the Narrows. In her first semester, she obtained an NPS research permit, trained six undergraduate and four graduate students as field assistants, and collaborated with the Yellowstone Park Archeologist to document Indigenous obsidian artifacts in her study areas.
