---
title: "Curiculum Vitae"
---

**Maggie Moss** \| [maggie.moss\@colostate.edu](mailto:Maggie.moss@colostate.edu) \| Fort Collins, CO 

**Professional Summary** \
Volcanology, Geochemistry, & Petrology PhD Candidate with four years of experience in academic research, writing, and data analysis. Strong research background in petrological and geochemical disciplines, as well as ample experience in planning and conducting fieldwork in volcanic environments. Aspiring to leverage skills to conduct petrological and geochemical research on the Yellowstone Plateau Volcanic Field basaltic plumbing system.  

**Education** \
**Ph.D. Geosciences, Colorado State University, Fort Collins, CO, expected December 2029**  

-   GPA: 4.09 \| McCallum Mineralogy & Petrology Scholar 
-   Supervisor: Dr. Lauren Harrison 
-   Dissertation: Igneous petrology, geochemistry and geochronology of basaltic plumbing systems through time at the Yellowstone Plateau Volcanic Field 

**Master of Urban Planning, NYU Wagner School of Public Service, NYC, NY, 2023** 

-   GPA: 3.87 \| Global Gallatin Fellowship in Urban Practice 
-   Capstone Project: The Impact of SFHA Designation on Neighborhood Development in NYC Post Hurricane Sandy  

**Bachelor of Science, Geological Sciences, George Washington University, Washington, D.C., 2019** 

-   Dean’s List, Departmental Honors, Magna Cum Laude 
-   Undergraduate Research Thesis: Analysis of Distal Lava Creek Tuff at Yellowstone Supervolcano: Insights into the thermal state of large-volume silicic magmas and the cooling history of related deposits 

|                                                    |
|----------------------------------------------------|
| **Honors & Awards**                                |
| Jack Kleinman Memorial Grant for Volcano Research  |
| Colorado Scientific Society Research Grant         |
| McCallum Mineralogy & Petrology Scholarship        |
| Joby Adams Geosciences Graduate Scholarship        |
| Gallatin Global Fellowship in Urban Practice       |
| Fulbright Research Scholar Semi-Finalist           |
| Luther Rice Undergraduate Research Scholarship     |
| KACIF Research Grant                               |
| Mineralogical Society of D.C. Research Award       |

**Publications** 

-   Field Guide to the Cascades Magmatic Arc (Forthcoming textbook in partnership with Dr. Richard Tollo with interest from Elsevier publishing) 
-   [Green, Healthy Schools: A Blueprint for Mayor Adams (Climate Works for All, 2022)](https://search.issuelab.org/resource/green-healthy-schools-a-blueprint-for-mayor-adams.html) 
-   Local Hiring for Green Infrastructure Development: One Path Toward Environmental & Economic Justice in NYC (ALIGN NY, Whitepaper, 2021) 

**Abstracts & Presentations** \
Moss, M., Myers, M., Mark, H., Yang, X., Cheng, Y., Gapenthin, R., Lizik, Y., Portner, D., Lee, D., Wu, S., Larsen, J., Coombs, M., Petrologic and Geophysical Synthesis of the Magmatic System at Akutan Volcano. AGU Fall Meeting, New Orleans, LA, December 2025. (First Author, Presenting) 

The Impact of SFHA Designation on Neighborhood Development in New York City Post Hurricane Sandy (NYU 2022) 

 

**Research**  

**Research Associate, Denver Museum of Nature & Science \| May 2025 - Present** 

**Intern, Denver Museum of Nature & Science \| May 2025 - Present** \
Conducted geologic research on the Rocky Mountains, Colorado Plateau, and Western U.S. basin and range geologic settings; creating paleomaps of the western US for use in forthcoming museum exhibits.  

**Research Assistant, Dr. Lauren Harrison, CSU Geosciences \| Jul 2025 - Present** \
Conducting field, geochronology, and geochemical research on Junction Butte Basalt and Undine Falls Basalt, oldest basaltic units of the Yellowstone Plateau Volcanic Field.  

**Data Analytics Fellow, Urban Democracy Lab \| Dec 2020 - Oct 2021** \
Conducted research in support of the Climate Leadership and Community Protection Act, resulting in publication, Green, Healthy Schools: A Blueprint for Mayor Adams (Climate Works for All, 2022).  

**Research Assistant, Dr. Richard Tollo, GWU Geology \| 2017-2019** \
Conducted research at Mt. Rogers, Yellowstone National Park, and the Cascades Magmatic Arc, resulting in forthcoming publication, Field Guide to the Cascades Magmatic Arc (Tollo).  \
 

**Teaching Experience** 

**Graduate Teaching Assistant** \
Colorado State University \| January 2025 – May 2025 \| Fort Collins, CO 

-   In collaboration with faculty, creates laboratory curriculum for undergraduate geology courses, gives weekly laboratory lectures in support of main lecture topics, and grades lab assignments and final exams.  
-   Igneous & Metamorphic Petrology (GEOL 364)  

\
**Graduate Teaching Assistant** \
New York University \| Aug 2020 – May 2021 & Jan 2022 - May 2022 \| New York, NY  

-   Taught statistical and data analytics laboratory course to NYU graduate students on topics such as housing finance, zoning, and transportation.  
-   Supported NYU Wagner faculty with curriculum research, online content creation for events, and other administrative projects to enhance the school’s profile and provide support to admitted students.  

**Undergraduate Teaching Assistant** \
George Washington University \| Aug 2017 - Dec 2018 \| Washington, D.C. 

-   In collaboration with tenured faculty, created laboratory curriculum for undergraduate introductory geology courses, gave weekly laboratory lectures in support of main lecture topics, and graded lab assignments and final exams.  
-   Served as laboratory learning support for undergraduate students in Mineralogy and Igneous & Metamorphic Petrology courses, and assisted professors with grading lab assignments. 

**Skills** \
ArcGIS \| R \| Stata \| MatLab \| Adobe Illustrator \| Microsoft Suite \| Chinese Language 

**Workshops/Short Courses** \
Diffusion Chronometry \| RUBION, Ruhr-University \| Bochum, Germany \| October 2025 \
Alaska Aleutian Arc Workshop \| Alaska Volcano Observatory \| Anchorage, AK \| May 2025  \
Exoplanets by the Lake II \| University of Munich \| Munich, Germany \| July 2024 
